"""
Required data passing classes
"""
from __future__ import annotations

from datetime import datetime
from typing import Union, Any
from enum import Enum
from dataclasses import dataclass, field
import uuid

class SignalType(Enum):
    BUY = 1
    SELL = 2

class OrderType(Enum):
    MARKET = 1
    BRACKET = 2
    STOP_LOSS = 3
    PROFIT_TAKER = 4
    TRAILING_STOP = 5

class OrderAction(Enum):
    BUY = 1
    SELL = 2

class OrderStatus(Enum):
    PENDING = 0
    FILLED = 1
    CANCELED = 2
    PENDING_SALE = 3

class OrderTimeInForce(Enum):
    DAY = 1 # For the day
    GTC = 2 # Good til Canceled
    IOC = 3 # Immediate or Cancel
    FOK = 4 # Fill or Kill
    OPG = 5 # At the open
    CLS = 6 # At the close

@dataclass
class PriceData:
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    trade_count: int = None
    vwap: float = None
    exchange: float = None

    @classmethod
    def from_dict(cls, data: dict, timestamp: datetime=None):
        """Create a PriceData instance from a dictionary."""
        if timestamp is not None:
            data['timestamp'] = timestamp
        return cls(**data)

@dataclass
class Position:
    symbol: str
    quantity: int

@dataclass
class MarketSignal:
    type: SignalType
    symbol: str
    strength: int # 0-100 to indicate how strong the signal is
    metadata: dict[str, Any] = field(default_factory=dict)

@dataclass
class TickResults:
    orders: list[Order] =  field(default_factory=lambda: []) # Orders generated by the portfolio for this tick
    output_tick: list[PriceData] = None # If the tick was changed it can be here, None otherwise
    metadata: dict[str, Any] = field(default_factory=dict)
    # Bracket orders to trigger manual sale on. Base class will set MANUAL_SALE=True,
    # call OM update, and apply portfolio changes if filled instantly.
    trigger_manual_sales: list[BracketOrder] = field(default_factory=lambda: [])
    # Cancel all pending orders of these types before submitting new orders.
    cancel_pending_order_types: list[OrderType] = field(default_factory=lambda: [])

@dataclass
class Order:
    placed_datetime: datetime
    action: OrderAction
    type: OrderType
    symbol: str
    price: float
    quantity: int
    cash: float
    executed_datetime: Union[None, datetime] = None
    time_in_force: OrderTimeInForce = OrderTimeInForce.GTC
    status: OrderStatus = OrderStatus.PENDING
    order_id: str = field(default_factory=lambda: f"local-{str(uuid.uuid4())}")
    tx_cost: float = 0.0
    parent_id: str = None
    platform_id: str = None
    trail_percent: float | None = None
    trail_price: float | None = None
    trail_hwm: float | None = None
    _child_orders: list[str] = field(default_factory=lambda: [])
    _child_orders_dict: dict[str, Order] = field(default_factory=lambda: {})
    processed_by_portfolio: bool = False

    def __str__(self):
        return (f"Order {self.order_id}: status: {self.status} {self.symbol}: {self.type} "
                f"quantity: {self.quantity} price: {self.price} "
                f"placed: {self.placed_datetime} executed: {self.executed_datetime} "
                f"processed by portfolio: {self.processed_by_portfolio}")

    def add_child_order(self, name: str, order: Union[None, Order]):
        if name not in self._child_orders:
            self._child_orders.append(name)
        self._child_orders_dict[name] = order

    def get_child_order_names(self) -> list[str]:
        return list(self._child_orders_dict.keys())

    def get_child_order(self, name: str) -> Order:
        return self._child_orders_dict[name]

    def update_trailing_stop(self, current_price: float) -> bool:
        """Tighten a sell trailing stop from current price. Returns True if stop moved."""
        if self.type != OrderType.TRAILING_STOP:
            raise ValueError("update_trailing_stop requires OrderType.TRAILING_STOP")
        if self.trail_percent is None and self.trail_price is None:
            raise ValueError("Trailing stop requires trail_percent or trail_price")
        old_price = self.price
        self.trail_hwm = max(self.trail_hwm or current_price, current_price)
        if self.trail_percent is not None:
            self.price = round(self.trail_hwm * (1.0 - self.trail_percent / 100.0), 2)
        else:
            self.price = round(self.trail_hwm - self.trail_price, 2)
        return self.price > old_price

    @staticmethod
    def create_market_order(
            symbol: str,
            order_action: OrderAction,
            quantity: int,
            tx_cost: float=0.0,
            current_tick:list[PriceData]=None,
    ) -> Order:
        """Create a MarketOrder instance."""
        if current_tick is not None:
            # Find the PriceData for this symbol
            pd = next((x for x in current_tick if x.symbol == symbol), None)
            placed_ts = pd.timestamp if pd else datetime.now()
        else:
            placed_ts = datetime.now()

        ret_val = Order(
            action=order_action,
            status=OrderStatus.PENDING,
            type=OrderType.MARKET,
            symbol=symbol,
            price=0.0,
            quantity=quantity,
            cash=0.0,
            tx_cost=tx_cost,
            placed_datetime=placed_ts,
        )
        return ret_val



class TrailingBracketOrder(Order):
    # TODO: Create a trailing bracket order
    pass

class BracketOrder(Order):

    MANUAL_SALE: bool = False
    SOLD_ORDER: Order = None
    intended_entry_price: float = 0.0

    @staticmethod
    def create_bracket_order(
            symbol: str,
            high_sell_price: float,
            low_sell_price: float,
            quantity: int,
            tx_cost: float=0.0,
            current_tick:list[PriceData]=None,
            ) -> BracketOrder:
        """
        Helper function to create a bracket order. It creates three orders
        the main buy order and two orders to take profit or stop loss
        Args:
            symbol:
            quantity:
            tx_cost:
            high_sell_price:
            low_sell_price:
            current_tick:
        Returns:
            List of orders starting with the main order, stop and profit take
        """

        high_sell_price = round(high_sell_price, 2)
        low_sell_price = round(low_sell_price, 2)

        if current_tick is not None:
            # Find the PriceData for this symbol
            pd = next((x for x in current_tick if x.symbol == symbol), None)
            placed_ts = pd.timestamp if pd else datetime.now()
        else:
            placed_ts = datetime.now()

        main_order = BracketOrder(
            action=OrderAction.BUY,
            type=OrderType.BRACKET,
            symbol=symbol,
            price=0.0,
            quantity=quantity,
            cash=0.0,
            tx_cost=tx_cost,
            status=OrderStatus.PENDING,
            placed_datetime=placed_ts,
        )

        stop_loss_order = Order(
            action=OrderAction.SELL,
            type=OrderType.STOP_LOSS,
            symbol=symbol,
            price=low_sell_price,
            quantity=quantity,
            cash=0,
            tx_cost=tx_cost,
            status=OrderStatus.PENDING,
            placed_datetime=placed_ts,
            parent_id=main_order.order_id,
        )

        profit_order = Order(
            action=OrderAction.SELL,
            type=OrderType.PROFIT_TAKER,
            symbol=symbol,
            price=high_sell_price,
            quantity=quantity,
            cash=0,
            tx_cost=tx_cost,
            status=OrderStatus.PENDING,
            placed_datetime=placed_ts,
            parent_id=main_order.order_id,
        )

        main_order.add_child_order("STOP", stop_loss_order)
        main_order.add_child_order("PROFIT", profit_order)
        main_order.add_child_order("MANUAL_ORDER", None)
        main_order.MANUAL_SALE = False
        return main_order

    @staticmethod
    def create_trailing_bracket_order(
            symbol: str,
            high_sell_price: float,
            quantity: int,
            trail_percent: float | None = None,
            trail_price: float | None = None,
            tx_cost: float=0.0,
            current_tick:list[PriceData]=None,
            ) -> BracketOrder:
        if trail_percent is None and trail_price is None:
            raise ValueError("Trailing bracket requires trail_percent or trail_price")
        if trail_percent is not None and trail_price is not None:
            raise ValueError("Trailing bracket supports trail_percent or trail_price, not both")
        main_order = BracketOrder.create_bracket_order(
            symbol=symbol,
            high_sell_price=high_sell_price,
            low_sell_price=0.0,
            quantity=quantity,
            tx_cost=tx_cost,
            current_tick=current_tick,
        )
        entry_price = 0.0
        if current_tick is not None:
            pd = next((x for x in current_tick if x.symbol == symbol), None)
            entry_price = pd.close if pd else 0.0
        stop_order = main_order.get_child_order("STOP")
        stop_order.type = OrderType.TRAILING_STOP
        stop_order.trail_percent = trail_percent
        stop_order.trail_price = trail_price
        stop_order.trail_hwm = entry_price or None
        if entry_price > 0:
            stop_order.update_trailing_stop(entry_price)
        return main_order
