logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console: true
  folder: "logs"  # Folder for log files
  filename: "trading.log"  # Set to null to disable file logging
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

data_provider:
  provider: data_providers.test_data_provider.TestDataProvider
  path: "data/SPXU.csv"
  truncate: 0
simulator:
  data_provider:
    provider: "data_providers.test_data_provider.TestDataProvider"
    path: "data/test_data.csv"
    truncate: 200
  algorithm:
    algorithm: "algorithms.test_algorithm.TestAlgorithm"
    # Algorithm specific configs go here
  order_manager:
    order_manager: "core.order_manager.OrderManager"
    # OM specific config goes here
  portfolio:
    portfolio: "core.portfolio.Portfolio"
    keep_history: true
    # PF specific config here
  alpaca:
    api_key: ""
    secret_key: ""