extends: ../tom_rsi_v2_aggressive_joint_hpo_split.yaml

data_provider:
  symbols: [LABU]

algorithm:
  symbol: LABU

portfolio:
  symbol: LABU

analysis:
  run_name: tom-rsi-v2-joint-hpo-return-seeking-LABU
  description: Return-seeking joint split HPO for LABU
